spring:
  datasource:
    url: jdbc:mysql://192.168.2.101:3306/genesis?userSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
